CREATE DATABASE IF NOT EXISTS testworkDB;

USE testworkDB;

CREATE TABLE IF NOT EXISTS dep (
  dep_id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  dep_name VARCHAR(64) UNIQUE NOT NULL
) CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS empl (
  emp_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  dep_id TINYINT UNSIGNED NOT NULL,
  emp_firstname VARCHAR(32),
  emp_lastname VARCHAR(32),
  emp_birthdate DATE,
  emp_email VARCHAR(64) UNIQUE NOT NULL,
  emp_post VARCHAR(64),
  emp_salary NUMERIC(6,2) UNSIGNED,
  FOREIGN KEY (dep_id) REFERENCES dep(dep_id) ON DELETE CASCADE ON UPDATE RESTRICT
) CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

